login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login),
    path('index/', views.index),
    path('register/', views.register),
    path('logout/', views.logout),
    path('result/<str:uuid_code>/', views.rusult, name='result'),
    path('result/', views.rusult, name='image_list'),
]

onlineocr/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include


urlpatterns = [
                  path('', include('login.urls')),
                  path('captcha/', include('captcha.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
import uuid

from django.db import models

from login.storage import ImageStorage


class User(models.Model):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    name = models.CharField(max_length=128, unique=True)  # 是否唯一
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32, choices=gender, default="男")
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    # 元数据
    class Meta:
        ordering = ["-c_time"]  # c_time降序排列
        verbose_name = "用户"
        verbose_name_plural = "用户"  # 复数


class Image(models.Model):
    user_name = models.CharField(max_length=128)  # 是否唯一
    uuid = models.CharField(max_length=128, default='', null=False)
    image = models.ImageField(upload_to='img/', blank=False, storage=ImageStorage())
    content = models.CharField(max_length=128, null=False, default='')

    def __str__(self):
        return 'media/%s' % self.image.name

login/forms.py
from django import forms
from captcha.fields import CaptchaField


class UserForm(forms.Form):
    username=forms.CharField(label='用户名',max_length=128,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username','autofoces':''}))
    # widget=forms.PasswordInput 相当于form表单里面的<input type='password'/>
    password=forms.CharField(label='密码',max_length=256,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
    captcha=CaptchaField(label='验证码')


class RegisterForm(forms.Form):
    gender=(('male',"男"),
            ('female',"女"))
    username = forms.CharField(label='用户名', max_length=128, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password1 = forms.CharField(label='密码', max_length=256,widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label='确认密码', max_length=256, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))
    email=forms.EmailField(label="邮箱地址",widget=forms.EmailInput(
        attrs={'class': 'form-control'}))
    sex=forms.ChoiceField(label="性别",choices=gender)
    captcha = CaptchaField(label='验证码')


class UploadImageForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=128, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}))
    image=forms.ImageField(label='图片',required=True)

login/views.py
import hashlib
import json
import uuid

import cv2
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect

from ocr.yolo_ocr import predict_model
from onlineocr import settings
from login import forms as login_forms
from login import models as login_models
import os


# Create your views here.
# 加密

def check_login(func):
    """
    查看session值用来判断用户是否已经登录
    :param func:
    :return:
    """

    def warpper(request, *args, **kwargs):
        if request.session.get('is_login', False):
            return func(request, *args, **kwargs)
        else:
            return redirect('/login/')

    return warpper


def hash_code(s, salt='sanfen'):  # s+salt一起进行加密
    h = hashlib.sha256()
    s = s + salt
    h.update(s.encode())  # upadte 只接受bytes类型
    return h.hexdigest()


@check_login
def index(request):
    if request.method == 'POST':
        image_form = login_forms.UploadImageForm(request.POST, request.FILES)
        message = request.FILES
        if image_form.is_valid():
            username = request.session['user_name']
            try:
                image = image_form.cleaned_data['image']
                img = login_models.Image.objects.create(image=image, user_name=username, content='')
                uuid_code = ''.join(str(uuid.uuid1()).split('-'))
                img.uuid = uuid_code
                img.save()

                res = predict_model(cv2.imread(img.image.path))
                alert_image = login_models.Image.objects.get(uuid=uuid_code)
                alert_image.content = json.dumps(res)
                alert_image.save()

                message_index = '上传成功！'
                return redirect('/result/%s' % alert_image.uuid)
            except Exception as e:
                print(e)
                message_index = '请求异常！'
                return render(request, 'login/index.html', locals())
        else:
            message_index = "上传失败"
            image_form = login_forms.UploadImageForm()
        return render(request, 'login/index.html', locals())
    else:
        image_form = login_forms.UploadImageForm()
        message = "请上传文件！"
        return render(request, 'login/index.html', locals())


def login(request):
    # 不允许重复登录
    if request.session.get('is_login', None):
        return redirect('/index/')
    if request.method == "POST":
        # username = request.POST.get('username')
        # password = request.POST.get('password')
        login_form = login_forms.UserForm(request.POST)
        message = '请检查填写的内容'
        # 数据验证
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')

            # 用户合法性判断
            try:
                # 数据查询API
                user = login_models.User.objects.get(name=username)
            except BaseException:
                message = '用户不存在！'
                # local()为python内置函数，返回当前所有的本地变量字典
                return render(request, 'login/login.html', locals())

            if user.password == hash_code(password):
                # session 字典中写入数据
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                return redirect('/index/')
        else:
            return render(request, 'login/login.html', locals())
    login_form = login_forms.UserForm()
    # 若不写locals() 则不能在login.html上调用{{ login_form }}
    return render(request, 'login/login.html', locals())


def register(request):
    if request.session.get('is_login', None):
        return redirect('/index/')
    if request.method == 'POST':
        register_form = login_forms.RegisterForm(request.POST)
        message = "请检查填写内容！"
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')
            email = register_form.cleaned_data.get('email')
            sex = register_form.cleaned_data.get('sex')
            if password1 != password2:
                message = "两次输入的密码不同！"
                return render(request, 'login/register.html', locals())
            else:
                same_name_user = login_models.User.objects.filter(name=username).count()
                if same_name_user != 0:
                    message = '用户名已存在！'
                    return render(request, 'login/register.html', locals())
                same_email_user = login_models.User.objects.filter(email=email).count()
                if same_email_user != 0:
                    message = '邮箱已被注册！'
                    return render(request, 'login/register.html', locals())
                # 写入数据库
                new_user = login_models.User()
                new_user.name = username
                new_user.password = hash_code(password1)
                new_user.email = email
                new_user.sex = sex
                new_user.save()
                return redirect('/login/')
        else:
            return render(request, 'login/register.html', locals())
    register_form = login_forms.RegisterForm()
    return render(request, 'login/register.html', locals())


@check_login
def logout(request):
    if not request.session.get('is_login', None):
        return redirect('/login/')
    # 清除session数据
    request.session.flush()
    return redirect('/login')


@check_login
def rusult(request, uuid_code=''):
    if request.method == 'GET':
        context = dict()
        if uuid_code == '':
            pictures = login_models.Image.objects.all()
            context['images']=[]
            for picture in pictures:
                images=dict()
                images['username'] = picture.user_name
                images['image_path'] = picture.image.name
                images['uuid'] = picture.uuid
                context['images'].append(images)
            print(context['images'])
            return render(request, 'login/image_list.html', context)
        else:
            username = request.session['user_name']
            if login_models.Image.objects.filter(user_name=username, uuid=uuid_code).count() != 0:
                picture = login_models.Image.objects.get(user_name=username, uuid=uuid_code)
                context['image'] = '%s' % picture.image.name
                print(picture.content)
                context['results'] = [] if picture.content == '' else json.loads(picture.content)
            return render(request, 'login/result.html', context)
    elif request.method == 'POST':
        pass

    # try:
    #
    #     contex=somewhere.handle_uploaded_file(picture)
    # except:
    #     return HttpResponse("查询失败")
    # else:
    #     return render(request, 'login/result.html', {'context':contex})

login/templates/login/image_list.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'login/css/register.css' %}" rel="stylesheet"/>
    <title>结果</title>
</head>
<body>
<h1>{{ request.session.user_name }}! 欢迎回来</h1>
<table class="table table-striped">
    <thead>
    <tr>
        <th>上传者</th>
        <th>图片</th>
    </tr>
    </thead>
    <tbody>
    {% for image in images %}
    <tr>
        <td>{{ image.username }}</td>
        <td>
            <div class="media">
                <div class="media-left media-middle">
                    <a href="{% url 'login:result' uuid_code=image.uuid %}"><img class="media-object"
                                                                                 style="width:300px"
                                                                                 src='/media/{{ image.image_path }}'></a>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<!-- 以下三者的引用顺序是固定的 -->
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

login/templates/login/index.html
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <!-- Bootstrap CSS -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'login/css/index.css' %}" rel="stylesheet"/>
    <title>首页</title>
</head>
<body>
<div class="container">
    <div class="col">
        <form action="/index/" method="post" enctype="multipart/form-data" class="form-index">
            <h1>{{ request.session.user_name }}! 欢迎回来  </h1>
            {% if message_index %}
            <div class="alert alert-warning">
                {{ message_index }}
            </div>
            {% endif %}
            {% csrf_token %}

            <div class="form-group">
                {{ image_form.as_p}}
            </div>
            <input type="submit" value="上传" class="btn btn-primary">
        </form>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

{# 以下三者的引用顺序是固定的#}
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

login/templates/login/login.html
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <!-- Bootstrap CSS -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'login/css/login.css' %}" rel="stylesheet"/>
    <title>登录</title>
  </head>
  <body>
    <div class="container">
            <div class="col">
              <form class="form-login" action="/login/" method="post">
                  {% if login_form.captcha.errors %}
                      <div class="alert alert-warning">{{ login_form.captcha.errors }}</div>
                  {% elif message %}
                  <div class="alert alert-warning">{{ message }}</div>
                  {% endif %}
                  {# 用于处理CSRF安全机制 #}
                  {% csrf_token %}
                  <h3 class="text-center">欢迎登录</h3>
                  <div class="form-group">
                      {{ login_form.username.label_tag }}
                      {{ login_form.username }}
                  </div>

                  <div class="form-group">
                      {{ login_form.password.label_tag }}
                      {{ login_form.password }}
                  </div>

                  <div class="form-group">
                      {{ login_form.captcha.label_tag }}
                      <p>
                      {{ login_form.captcha}}
                  </div>
                  <div class="form-group">
                  <a href="/register/" class="text-success "><ins>新用户注册</ins></a>
                  <button type="submit" class="btn btn-primary float-right">登录</button>
                  </div>
              </form>
            </div>
    </div> <!-- /container -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    {#    以下三者的引用顺序是固定的#}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

  </body>
</html>

login/templates/login/register.html
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <!-- Bootstrap CSS -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'login/css/register.css' %}" rel="stylesheet"/>
    <title>注册</title>
  </head>
  <body>
    <div class="container">
            <div class="col">
              <form class="form-register" action="/register/" method="post">
                  {% if register_form.captcha.errors %}
                      <div class="alert alert-warning">{{ rehister_form.captcha.errors }}</div>
                  {% elif message %}
                  <div class="alert alert-warning">{{ message }}</div>
                  {% endif %}
                  {# 用于处理CSRF安全机制 #}
                  {% csrf_token %}
                  <h3 class="text-center">欢迎注册</h3>

                  <div class="form-group">
                      {{ register_form.username.label_tag }}
                      {{ register_form.username }}
                  </div>

                  <div class="form-group">
                      {{ register_form.password1.label_tag }}
                      {{ register_form.password1 }}
                  </div>

                  <div class="form-group">
                      {{ register_form.password2.label_tag }}
                      {{ register_form.password2 }}
                  </div>
                  <div class="form-group">
                      {{ register_form.email.label_tag }}
                      {{ register_form.email }}
                  </div>
                  <div class="form-group">
                      {{ register_form.sex.label_tag }}
                      {{ register_form.sex }}
                  </div>
                  <div class="form-group">
                      {{ register_form.captcha.label_tag }}
                      <p>
                      {{ register_form.captcha}}
                  </div>
                  <div class="form-group">
                  <a href="/login/" class="text-success "><ins>直接登录</ins></a>
                  <button type="submit" class="btn btn-primary float-right">注册</button>
                  </div>
              </form>
            </div>
    </div> <!-- /container -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    {#    以下三者的引用顺序是固定的#}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

  </body>
</html>

login/templates/login/result.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'login/css/register.css' %}" rel="stylesheet"/>
    <title>结果</title>
</head>
<body>
<h1>{{ request.session.user_name }}! 欢迎回来 <a href="{% url 'login:image_list'  %}">图片列表</a></h1>
<table class="table table-striped">
    <thead>
    <tr>
        <th>上传者</th>
        <th>图片</th>
        <th>识别结果</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ request.session.user_name }}</td>
        <td>
            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="width:300px" src='/media/{{ image }}' class="img-responsive">
                </div>
            </div>
        </td>
        <td style="font-size: 30px">
            {% for result in results %}
            <p>{{ result.text }}</p>
            {% endfor %}
        </td>
    </tr>
    </tbody>
</table>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<!-- 以下三者的引用顺序是固定的 -->
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>